"""origen_score_nullable_temperatura_desconocido

Revision ID: 9e45011e26e0
Revises: faf8f65e853e
Create Date: 2026-06-10 19:35:44.684440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e45011e26e0'
down_revision: Union[str, None] = 'faf8f65e853e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'origen',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('leads', 'score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('leads', 'origen',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
