"""e02 modelos

Revision ID: 344795bfdab6
Revises: 
Create Date: 2026-06-10 15:39:28.175402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '344795bfdab6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Necesaria para gen_random_uuid() (server_default de las PK UUID).
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asesores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('disponible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asesores_tenant_id'), 'asesores', ['tenant_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('contacto', sa.String(), nullable=True),
    sa.Column('origen', sa.String(), nullable=False),
    sa.Column('idioma', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('temperatura', sa.String(), server_default=sa.text("'frio'"), nullable=False),
    sa.Column('estado', sa.String(), server_default=sa.text("'nuevo'"), nullable=False),
    sa.Column('perfil', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('asesor_id', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asesor_id'], ['asesores.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_asesor_id'), 'leads', ['asesor_id'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_lead_id'), 'eventos', ['lead_id'], unique=False)
    op.create_table('mensajes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_lead_id'), 'mensajes', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajes_lead_id'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_eventos_lead_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_asesor_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_asesores_tenant_id'), table_name='asesores')
    op.drop_table('asesores')
    op.drop_table('tenants')
    # ### end Alembic commands ###
